name: Create Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
      name: Create Release
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Create Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          with:
            tag_name: ${{ github.run_id}}
            release_name: Release ${{ github.run_id }}
            body: |
              Este body se puede configurar con templates y otras herramientas 
            draft: false
            prerelease: false